### ISSUE TITLE
Comments on Command line and installation on J4

### ISSUE THREAD

**Issue by ghazal** [alexandreelise/plg_system_rewritenosubcategories#1]
Your way to install the plugin via the command line didn't work for me. 
Maybe it's related to some differences between mac and linux, but I wouldn't bet on it.
Here is my suggestion : 

Environment:
macOS Catalina
iTerm (instead of Terminal)
PHP 8.0.2
Joomla 4.0.0-beta8-dev 

Goal:
Use "Discover" 

Method:
```  cd /path/to/file/htdocs/joomla4/plugins/system ``` 

```  git clone https://github.com/alexandreelise/plg_system_rewritenosubcategories ``` 
PS : .git not mandatory

* Files installed in the proper folder
* Rename folder from  "plg_system_rewritenosubcategories" to "rewritenosubcategories"
* Extract .php and .xml file from "rewritenosubcategories/src" and place them in root of folder 
* Do "Discover" and "Install"
* There you are, plugin installed and working.

A bit of a hack (un peu de la bidouille mais bon ...)...

**Comment by alexandreelise** [comment]
Hello @ghazal,
Thanks for your feedback and testing on a different environment.
The plugin zip package is already in the build folder of this repo. [This link for the extension](https://github.com/alexandreelise/plg_system_rewritenosubcategories/blob/master/build/plg_system_rewritenosubcategories_202102212200.zip)
The instructions I provided is to build the extension yourself 
using make and the provided Makefile.
Moreover I built it with Joomla! 3.9 in mind but as you successfully installed it on the latest nightly build of 4 it's a good thing.
Thanks anyway for reporting this glad you made it work yourself. take care and have a great day.
Closing for now.
